version: '3.8'
services:
  spring-backend:
    image: spring-app:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    # environment:
    #   - SERVER_PORT= 8082
    #   - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/genshjdbc:postgresql://service-db/gensh